# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pentagram', '0002_auto_20160715_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='counter_like',
            field=models.IntegerField(default=0),
        ),
    ]
