# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pentagram', '0005_auto_20160719_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
