# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pentagram', '0007_auto_20160719_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
    ]
